"""test2

Revision ID: f0e78c590986
Revises: e5aed539488b
Create Date: 2023-04-05 10:44:30.767825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e78c590986'
down_revision = 'e5aed539488b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bakery_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_baked_goods_bakery_bakeries', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_baked_goods_bakery_id_bakeries'), 'bakeries', ['bakery_id'], ['id'])
        batch_op.drop_column('bakery')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bakery', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_baked_goods_bakery_id_bakeries'), type_='foreignkey')
        batch_op.create_foreign_key('fk_baked_goods_bakery_bakeries', 'bakeries', ['bakery'], ['id'])
        batch_op.drop_column('bakery_id')

    # ### end Alembic commands ###
